# Chat messages stored by Ruben V
# Datasources: https://ruben.verborgh.org/profile/
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sioc: <http://rdfs.org/sioc/ns#>
SELECT ?message ?author WHERE {
  ?id sioc:content ?message.
  ?id foaf:maker ?author.
}
